import React, { createContext, useContext, useState } from "react";
import type { AgentModel } from "@/types/models/Agent.model";
import type { ConversationModel } from "@/types/models/Conversation.model";
import type { MessageModel } from "@/types/models/Message.model";
import type {
  ConversationsContextProps,
  ConversationsProviderProps,
} from "@/types/contexts/ConversationsContextTypes";

const ConversationsContext = createContext<ConversationsContextProps>(
  {} as ConversationsContextProps
);

// eslint-disable-next-line react-refresh/only-export-components
export const useConversations = () => useContext(ConversationsContext);

export const ConversationsProvider: React.FC<ConversationsProviderProps> = ({
  children,
}) => {
  const [conversations, setConversations] = useState<ConversationModel[]>([]);

  const createConversation = (title: string, agentId: string) => {
    const conversation: ConversationModel = {
      id: crypto.randomUUID(),
      title,
      agentId,
      agentConfigurationId: agentId,
      messages: [],
      lastMessageAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    setConversations((prev) => [conversation, ...prev]);
    return conversation;
  };

  const sendMessage = (conversationId: string, content: string) => {
    setConversations((prev) =>
      prev.map((conv) => {
        if (conv.id !== conversationId) return conv;

        const userMessage: MessageModel = {
          id: `msg-${crypto.randomUUID()}`,
          content,
          role: "user",
          conversationId,
          createdAt: new Date(),
        };

        const assistantMessage: MessageModel = {
          id: `msg-${crypto.randomUUID()}`,
          content:
            "This is a simulated response from the AI agent. In a real application, this would be generated by the LLM.",
          role: "assistant",
          conversationId,
          createdAt: new Date(Date.now() + 1000),
        };

        return {
          ...conv,
          messages: [...(conv.messages ?? []), userMessage, assistantMessage],
        };
      })
    );
  };

  const startConversationForAgent = (agent: AgentModel) => {
    return createConversation(`Chat with ${agent.name ?? agent.id}`, agent.id);
  };

  return (
    <ConversationsContext.Provider
      value={{
        conversations,
        createConversation,
        sendMessage,
        startConversationForAgent,
      }}
    >
      {children}
    </ConversationsContext.Provider>
  );
};
