import React, { createContext, useContext, useState } from "react";
import type { AgentConfig } from "@/types/models/AgentModel";
import type { Conversation } from "@/types/models/ConversationModel";
import type { Message } from "@/types/models/MessageModel";
import { mockConversations } from "@/lib/mockData";
import type {
  ConversationsContextProps,
  ConversationsProviderProps,
} from "@/types/contexts/ConversationsContextTypes";

const ConversationsContext = createContext<ConversationsContextProps>(
  {} as ConversationsContextProps
);

// eslint-disable-next-line react-refresh/only-export-components
export const useConversations = () => useContext(ConversationsContext);

export const ConversationsProvider: React.FC<ConversationsProviderProps> = ({
  children,
}) => {
  const [conversations, setConversations] =
    useState<Conversation[]>(mockConversations);

  const createConversation = (title: string, agentId: string) => {
    const conversation: Conversation = {
      id: crypto.randomUUID(),
      title,
      agentId,
      messages: [],
      createdAt: new Date(),
    };
    setConversations((prev) => [conversation, ...prev]);
    return conversation;
  };

  const sendMessage = (conversationId: string, content: string) => {
    setConversations((prev) =>
      prev.map((conv) => {
        if (conv.id !== conversationId) return conv;

        const userMessage: Message = {
          id: `msg-${crypto.randomUUID()}`,
          content,
          role: "user",
          timestamp: new Date(),
        };

        const assistantMessage: Message = {
          id: `msg-${crypto.randomUUID()}`,
          content:
            "This is a simulated response from the AI agent. In a real application, this would be generated by the LLM.",
          role: "assistant",
          timestamp: new Date(Date.now() + 1000),
        };

        return {
          ...conv,
          messages: [...conv.messages, userMessage, assistantMessage],
        };
      })
    );
  };

  const startConversationForAgent = (agent: AgentConfig) => {
    return createConversation(`Chat with ${agent.title}`, agent.id);
  };

  return (
    <ConversationsContext.Provider
      value={{
        conversations,
        createConversation,
        sendMessage,
        startConversationForAgent,
      }}
    >
      {children}
    </ConversationsContext.Provider>
  );
};
